### ISSUE TITLE
iFL Preferences, host is localhost: java.lang.IllegalArgumentException: http://localhost in log

### ISSUE THREAD

**Issue by brita-sed** [geryxyz/iFL4Eclipse#209]
**Precondition**
* .../eclipse.exe has launched.  
* iFL plugin has been installed. 

**Steps**
1. Select a project.
1. Click iFL button. 
1. Window / Preferences > iFL Preferences. 
1. Give the following data: 
![ifl_preferences](https://user-images.githubusercontent.com/16755484/118137345-65c24a00-b405-11eb-80a6-d6cadead6194.JPG)
1. Click Apply and Close

**Expected results**
* In case of valid data: changes have been moded
* In csase of invalid data: an error popup will appear. 

**Received results**
* Error in log file.
```
java.lang.IllegalArgumentException: http://localhost
	at org.apache.tinkerpop.gremlin.driver.Cluster$Builder.addContactPoint(Cluster.java:976)
	at org.apache.tinkerpop.gremlin.driver.Cluster$Builder.<init>(Cluster.java:597)
	at org.apache.tinkerpop.gremlin.driver.Cluster$Builder.<init>(Cluster.java:554)
	at org.apache.tinkerpop.gremlin.driver.Cluster.build(Cluster.java:166)
```
Log: 
[illegal_argument_localhost_log.txt](https://github.com/InteractiveFaultLocalization/iFL4Eclipse/files/6472922/illegal_argument_localhost_log.txt)

**Related issue:**
* #105

**Environment:**
* Package: https://github.com/InteractiveFaultLocalization/iFL4Eclipse/releases/tag/V3.0.0.0
* Operating System: Windows 10 Pro, 64 bit
* Eclipse version: 2019-09 R (4.13.0)

**Comment by brita-sed** [comment]
After loading scores this preference cause other troubles: 
[unexpected_localhost.txt](https://github.com/InteractiveFaultLocalization/iFL4Eclipse/files/6473040/unexpected_localhost.txt)

![unexpected_localhost](https://user-images.githubusercontent.com/16755484/118139588-cc486780-b407-11eb-846b-1b778440680b.JPG)

**Comment by Dhorvath1294** [comment]
https://github.com/InteractiveFaultLocalization/iFL4Eclipse/releases/tag/V3.4.209.1

**Comment by brita-sed** [comment]
There isn't any error message in log retesting this bug, corrected.
